export const puzzleLevels = [
    {
      level: 'easy',
      id: 1,
      puzzles: [
        {
          id: 1,
          image: require('../../assets/images/puzzle/easy/Prop=01.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/easy/1/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/easy/1/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/easy/1/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/easy/1/Prop=04.jpg') },
          ],
        },
        {
          id: 2,
          image: require('../../assets/images/puzzle/easy/Prop=02.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/easy/2/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/easy/2/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/easy/2/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/easy/2/Prop=04.jpg') },
          ],
        },
        {
          id: 3,
          image: require('../../assets/images/puzzle/easy/Prop=03.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/easy/3/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/easy/3/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/easy/3/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/easy/3/Prop=04.jpg') },
          ],
        },
        {
          id: 4,
          image: require('../../assets/images/puzzle/easy/Prop=04.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/easy/4/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/easy/4/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/easy/4/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/easy/4/Prop=04.jpg') },
          ],
        },
      ],
    },
    {
      level: 'normal',
      id: 2,
      puzzles: [
        {
          id: 1,
          image: require('../../assets/images/puzzle/normal/Prop=01.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/normal/1/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/normal/1/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/normal/1/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/normal/1/Prop=04.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/normal/1/Prop=05.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/normal/1/Prop=06.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/normal/1/Prop=07.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/normal/1/Prop=08.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/normal/1/Prop=09.jpg') },
          ],
        },
        {
            id: 2,
            image: require('../../assets/images/puzzle/normal/Prop=02.png'),
            pieces: [
              { id: 1, image: require('../../assets/images/puzzle/normal/2/Prop=01.jpg') },
              { id: 2, image: require('../../assets/images/puzzle/normal/2/Prop=02.jpg') },
              { id: 3, image: require('../../assets/images/puzzle/normal/2/Prop=03.jpg') },
              { id: 4, image: require('../../assets/images/puzzle/normal/2/Prop=04.jpg') },
              { id: 5, image: require('../../assets/images/puzzle/normal/2/Prop=05.jpg') },
              { id: 6, image: require('../../assets/images/puzzle/normal/2/Prop=06.jpg') },
              { id: 7, image: require('../../assets/images/puzzle/normal/2/Prop=07.jpg') },
              { id: 8, image: require('../../assets/images/puzzle/normal/2/Prop=08.jpg') },
              { id: 9, image: require('../../assets/images/puzzle/normal/2/Prop=09.jpg') },
            ],
          },
          {
            id: 3,
            image: require('../../assets/images/puzzle/normal/Prop=03.png'),
            pieces: [
              { id: 1, image: require('../../assets/images/puzzle/normal/3/Prop=01.jpg') },
              { id: 2, image: require('../../assets/images/puzzle/normal/3/Prop=02.jpg') },
              { id: 3, image: require('../../assets/images/puzzle/normal/3/Prop=03.jpg') },
              { id: 4, image: require('../../assets/images/puzzle/normal/3/Prop=04.jpg') },
              { id: 5, image: require('../../assets/images/puzzle/normal/3/Prop=05.jpg') },
              { id: 6, image: require('../../assets/images/puzzle/normal/3/Prop=06.jpg') },
              { id: 7, image: require('../../assets/images/puzzle/normal/3/Prop=07.jpg') },
              { id: 8, image: require('../../assets/images/puzzle/normal/3/Prop=08.jpg') },
              { id: 9, image: require('../../assets/images/puzzle/normal/3/Prop=09.jpg') },
            ],
          },
          {
            id: 4,
            image: require('../../assets/images/puzzle/normal/Prop=04.png'),
            pieces: [
              { id: 1, image: require('../../assets/images/puzzle/normal/4/Prop=01.jpg') },
              { id: 2, image: require('../../assets/images/puzzle/normal/4/Prop=02.jpg') },
              { id: 3, image: require('../../assets/images/puzzle/normal/4/Prop=03.jpg') },
              { id: 4, image: require('../../assets/images/puzzle/normal/4/Prop=04.jpg') },
              { id: 5, image: require('../../assets/images/puzzle/normal/4/Prop=05.jpg') },
              { id: 6, image: require('../../assets/images/puzzle/normal/4/Prop=06.jpg') },
              { id: 7, image: require('../../assets/images/puzzle/normal/4/Prop=07.jpg') },
              { id: 8, image: require('../../assets/images/puzzle/normal/4/Prop=08.jpg') },
              { id: 9, image: require('../../assets/images/puzzle/normal/4/Prop=09.jpg') },
            ],
          },
      ],
    },
    {
      level: 'hard',
      id: 3,
      puzzles: [
        {
          id: 1,
          image: require('../../assets/images/puzzle/hard/Prop=01.png'),
          pieces: [
            { id: 1, image: require('../../assets/images/puzzle/hard/1/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/hard/1/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/hard/1/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/hard/1/Prop=04.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/1/Prop=05.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/1/Prop=06.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/1/Prop=07.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/1/Prop=08.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/1/Prop=09.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/1/Prop=10.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/1/Prop=11.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/1/Prop=12.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/1/Prop=13.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/1/Prop=14.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/1/Prop=15.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/1/Prop=16.jpg') },
          ],
        },
        {
        id: 2,
        image: require('../../assets/images/puzzle/hard/Prop=02.png'),
        pieces: [
            { id: 1, image: require('../../assets/images/puzzle/hard/2/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/hard/2/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/hard/2/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/hard/2/Prop=04.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/2/Prop=05.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/2/Prop=06.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/2/Prop=07.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/2/Prop=08.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/2/Prop=09.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/2/Prop=10.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/2/Prop=11.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/2/Prop=12.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/2/Prop=13.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/2/Prop=14.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/2/Prop=15.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/2/Prop=16.jpg') },
            ],
          },
          {
        id: 3,
        image: require('../../assets/images/puzzle/hard/Prop=03.png'),
        pieces: [
            { id: 1, image: require('../../assets/images/puzzle/hard/3/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/hard/3/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/hard/3/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/hard/3/Prop=04.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/3/Prop=05.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/3/Prop=06.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/3/Prop=07.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/3/Prop=08.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/3/Prop=09.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/3/Prop=10.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/3/Prop=11.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/3/Prop=12.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/3/Prop=13.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/3/Prop=14.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/3/Prop=15.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/3/Prop=16.jpg') },
            ],
            },
      {
        id: 4,
        image: require('../../assets/images/puzzle/hard/Prop=04.png'),
        pieces: [
            { id: 1, image: require('../../assets/images/puzzle/hard/4/Prop=01.jpg') },
            { id: 2, image: require('../../assets/images/puzzle/hard/4/Prop=02.jpg') },
            { id: 3, image: require('../../assets/images/puzzle/hard/4/Prop=03.jpg') },
            { id: 4, image: require('../../assets/images/puzzle/hard/4/Prop=04.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/4/Prop=05.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/4/Prop=06.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/4/Prop=07.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/4/Prop=08.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/4/Prop=09.jpg') },
            { id: 5, image: require('../../assets/images/puzzle/hard/4/Prop=10.jpg') },
            { id: 6, image: require('../../assets/images/puzzle/hard/4/Prop=11.jpg') },
            { id: 7, image: require('../../assets/images/puzzle/hard/4/Prop=12.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/4/Prop=13.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/4/Prop=14.jpg') },
            { id: 8, image: require('../../assets/images/puzzle/hard/4/Prop=15.jpg') },
            { id: 9, image: require('../../assets/images/puzzle/hard/4/Prop=16.jpg') },
            ],
            },
      ],
    },
  ];
  